find . -name '*.aux' -exec rm '{}' +
find . -name '*.bbl' -exec rm '{}' +
find . -name '*.blg' -exec rm '{}' +
find . -name '*.lof' -exec rm '{}' +
find . -name '*.log' -exec rm '{}' +
find . -name '*.lop' -exec rm '{}' +
find . -name '*.lot' -exec rm '{}' +
find . -name '*.pdf' -exec rm '{}' +
find . -name '*.toc' -exec rm '{}' +
